### ISSUE TITLE
Fix Matic in swap

### ISSUE THREAD

**Issue by orbitmechanic** [orbitmechanic/USAMobile#130]
Address is wonky.  '0xeeee...eeee'

**Comment by orbitmechanic** [comment]
Real address should be 0x0000000000000000000000000000000000001010

**Comment by orbitmechanic** [comment]
Consider Tx hash: 0x03e1e8ca577396c27ccb62c6341982928721b9691dd4b14cc088eaa24bd5156b

**Comment by orbitmechanic** [comment]
<img width="646" alt="Screen Shot 2021-11-10 at 6 01 35 PM" src="https://user-images.githubusercontent.com/56613757/141207645-01eddf0c-98b7-4a2f-818a-93d3cb5e569e.png">

**Comment by git-tn** [comment]
Hey @orbitmechanic , the MATIC address on Polygon network is 0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.
If we update the MATIC address to 0x00...01010, then the 1inch quote API fails with bad request.

please check 1inch API documentation and API response here: 
https://api.1inch.exchange/v3.0/137/tokens

![image](https://user-images.githubusercontent.com/16561299/141273102-1b7d9851-5ac8-4a0f-ac88-50e599761947.png)


We also have to update the TokenList.json, MATIC address is also set to 0x00...01010. it's also causing issues in swap.

![image](https://user-images.githubusercontent.com/16561299/141274070-f65aa15d-de71-435c-a94a-5fe24b9aa66b.png)

![image](https://user-images.githubusercontent.com/16561299/141274293-b0246e2b-3f71-4c18-971d-ba08e1f6fb62.png)

![image](https://user-images.githubusercontent.com/16561299/141274433-2d85edd2-df88-4648-b795-8eaca6b1f991.png)

**Comment by orbitmechanic** [comment]
It seems like the 0xeeee address is internal only to 1Inch?  I knew I got it from somewhere.  Thanks for tracking it down.  Can we isolate it to just the 1Inch  swap functions?  It's causing problems elsewhere it seems.  Joey and Farid are complaining that's not the real Matic address on-chain.  They say it's supposed to be 0x1010.

**Comment by git-tn** [comment]
Okay, I will update

**Comment by orbitmechanic** [comment]
Investigate which aggregator is being used.
Consider wrapped matic because it has a contract.

**Comment by ctrl030** [comment]
From my understanding it seems that this address is a placeholder inside the 1inch dapp, used for network native tokens. Originally used for Ethereum on Ethereum mainnet, then carried over for Matic on Polygon mainnet. The address was probably specifically chosen since it does not represent any currency on either of these networks. It might get a bit messy if we have to use this placeholder address for Matic when trading on 1inch, but then use the normal address for Matic everywhere else.
As a solution for this we could look into using wrapped Matic, WMATIC (0x0d500b1d8e8ef31e21c99d1db9a6444d3adf1270 on polygon mainnet) as much as we can. Using WETH seems to work very well on Ethereum mainnet, for ex. on Uniswap. WMATIC and WETH should behave like standard ERC20 tokens and therefore be easy to handle, without needing extra logic. This might be an additional thing to explain to end users though, so both approaches seem to have their pros and cons.

**Comment by orbitmechanic** [comment]
Swaps now work from Matic via 1Inch to #randomtoken.
