### ISSUE TITLE
Rig global colors to new design scheme (2 hours)

### ISSUE THREAD

**Issue by orbitmechanic** [orbitmechanic/USAMobile#246]
Borg/absolve/absorb the design team's color pallet into our ap's Material global color configurations. Refer to pallet as described in [Figma design document]. 
These should become named global styles available everywhere in both our ap website first and then our mobile ap. (https://www.figma.com/file/UObNY2oCbSchL4pPVi8QSX/USA-Wallet-%2F-APP?node-id=0%3A1):
<img width="572" alt="Screen Shot 2021-12-09 at 8 45 07 AM" src="https://user-images.githubusercontent.com/56613757/145408129-763f2b0f-19d6-44d3-891a-6f33dcd8db92.png">

**Comment by nyousaf47** [comment]
@orbitmechanic to override MUI Colors, I need Colors palette like this. 
https://mui.com/customization/palette/
colors Name and its 3 version and 4th Text Color
1. light
2. main
3. dark 
4. Text color on that color

Otherwise I have to use all colors as a variables , as we are doing for shadow or borderRadius. 
Will discuss in Status.

**Comment by nyousaf47** [comment]
I need above color Plate updated on design side, I can use 4 colors in MUI for single color. 
If Design team does not give this , I have to use all colors as variable , which is not good approach but we can follow.

**Comment by orbitmechanic** [comment]
![image](https://user-images.githubusercontent.com/56613757/146581694-3800cb1d-1a0a-44b5-911b-1cb8f3235dd7.png)
Latest color scheme is as above.

**Comment by orbitmechanic** [comment]
Working on translating to @Material.io

**Comment by orbitmechanic** [comment]
Looks pretty good!
