### ISSUE TITLE
Swap Tx's are blocked by missing allowances?  Especially on Matic/ETH/<native currency>

### ISSUE THREAD

**Issue by orbitmechanic** [orbitmechanic/USAMobile#91]
Not sure if this is all tokens, or just the network's native currency.  Probably a Moralis call that needs to differentiate between native and ERC20 transactions.  
![Screen Shot 2021-11-02 at 11 53 44 AM](https://user-images.githubusercontent.com/56613757/139887001-e8bcb0f5-2204-4617-92a9-3fabe92b52b2.png)

**Comment by git-tn** [comment]
@orbitmechanic ,  seems you have `fromToken` as `MATIC` in screenshot, I filtered out the `fromToken` from toList, so you won't see `MATIC` if you have selected `MATIC` as from. Please try to use different token as from and you will be seeing MATIC in the list, I attached screenshot. Also, ETH is also filtered out because it's from other network.

![image](https://user-images.githubusercontent.com/16561299/139998339-c7948e94-5191-48f0-a39a-063e0d2704ba.png)

![image](https://user-images.githubusercontent.com/16561299/139998645-2a7b4008-0a4d-4ef1-a972-d48abede4275.png)

**Comment by orbitmechanic** [comment]
That's actually not a valid solution.  What do I do with my MATIC now?
And besides, that does not seem to be the error.  Here's me trying to swap MANA for USDC and getting about the same error.
![Screen Shot 2021-11-03 at 11 23 21 AM](https://user-images.githubusercontent.com/56613757/140090157-7a6ccf5a-81fd-4321-ac93-41e10effa541.png)

**Comment by git-tn** [comment]
Okay, I'll investigate this issue Today and hopefully fix it.

**Comment by orbitmechanic** [comment]
Resolved via upgrading Swap to the Moralis.io swap function.
